name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /etc/ssl

            echo "${{ secrets.SSL_CERTIFICATE }}" | sudo tee /etc/ssl/cert.pem > /dev/null
            echo "${{ secrets.SSL_PRIVATE_KEY }}" | sudo tee /etc/ssl/key.pem > /dev/null

            sudo chmod 644 /etc/ssl/cert.pem
            sudo chmod 600 /etc/ssl/key.pem

            sudo docker pull kiiier/super-aws-api:latest
            
            sudo docker stop super-aws-api || true
            sudo docker rm super-aws-api || true
            
            sudo docker run -d --name super-aws-api -p 443:443 \
              -e CERT_PATH="/etc/ssl/cert.pem" \
              -e KEY_PATH="/etc/ssl/key.pem" \
              -v /etc/ssl:/etc/ssl:ro \
              kiiier/super-aws-api:latest
