name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            sudo docker pull kiiier/super-aws-api:latest
            sudo docker stop super-aws-api || true
            sudo docker rm super-aws-api || true
            sudo docker run -d --name super-aws-api -p 80:8080 kiiier/super-aws-api:latest
