name: Setup SSL Renewal Script and Cron Job

on:
  workflow_dispatch:

jobs:
  setup-renewal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy SSL renewal script to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "script.sh"
          target: "/home/ubuntu/script.sh"

      - name: Execute script initially and setup cron job
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/script.sh
            /home/ubuntu/script.sh
            (crontab -l 2>/dev/null; echo "0 0 1 */2 * /home/ubuntu/script.sh") | crontab -
            sudo service cron reload